<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="11.394" tests="3" failures="1">
  <testsuite name="Root Suite" timestamp="2025-10-16T14:25:29" tests="0" file="..\tests\e2e\login.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Login E2E" timestamp="2025-10-16T14:25:29" tests="3" time="11.389" failures="1">
    <testcase name="Login E2E Carga la p치gina de login" time="1.839" classname="Carga la p치gina de login">
    </testcase>
    <testcase name="Login E2E Muestra error con credenciales inv치lidas" time="0.000" classname="Muestra error con credenciales inv치lidas">
      <failure message="Timed out retrying after 5000ms: Expected to find content: &apos;/error|incorrecto|credenciales/i&apos; but never did." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 5000ms: Expected to find content: '/error|incorrecto|credenciales/i' but never did.
    at Context.eval (webpack://frontend/../tests/e2e/login.cy.js:19:73)]]></failure>
    </testcase>
    <testcase name="Login E2E Login exitoso redirige a Home" time="2.258" classname="Login exitoso redirige a Home">
    </testcase>
  </testsuite>
</testsuites>