<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="3.975" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2025-10-16T04:27:55" tests="0" file="..\tests\e2e\login.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Prueba básica de la página de inicio" timestamp="2025-10-16T04:27:55" tests="1" time="3.959" failures="1">
    <testcase name="Prueba básica de la página de inicio Debe cargar la página y verificar el título" time="0.000" classname="Debe cargar la página y verificar el título">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:5000/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; AggregateError

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:5000/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > AggregateError

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
    at <unknown> (http://localhost:54991/__cypress/runner/cypress_runner.js:134323:74)
    at visitFailedByErr (http://localhost:54991/__cypress/runner/cypress_runner.js:133897:12)
    at <unknown> (http://localhost:54991/__cypress/runner/cypress_runner.js:134322:11)
    at tryCatcher (http://localhost:54991/__cypress/runner/cypress_runner.js:1777:23)
    at Promise._settlePromiseFromHandler (http://localhost:54991/__cypress/runner/cypress_runner.js:1489:31)
    at Promise._settlePromise (http://localhost:54991/__cypress/runner/cypress_runner.js:1546:18)
    at Promise._settlePromise0 (http://localhost:54991/__cypress/runner/cypress_runner.js:1591:10)
    at Promise._settlePromises (http://localhost:54991/__cypress/runner/cypress_runner.js:1667:18)
    at _drainQueueStep (http://localhost:54991/__cypress/runner/cypress_runner.js:2377:12)
    at _drainQueue (http://localhost:54991/__cypress/runner/cypress_runner.js:2370:9)
    at Async._drainQueues (http://localhost:54991/__cypress/runner/cypress_runner.js:2386:5)
    at Async.drainQueues (http://localhost:54991/__cypress/runner/cypress_runner.js:2256:14)
From Your Spec Code:
    at Context.eval (webpack://frontend/../tests/e2e/login.cy.js:6:11)

From Node.js Internals:
  AggregateError [ECONNREFUSED]: 
      at internalConnectMultiple (node:net:1134:18)
      at afterConnectMultiple (node:net:1715:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>